Arb mainnet
Synthetixio/synthetix-deployments pull request #150
Opened 2024-03-15 11:53 UTC by dbeal-eth

2024-03-15 12:04 UTC, noisekit approved these changes

2024-03-15 12:06 UTC, noisekit commented on tomls/collaterals/weth.toml
> -include = ["../oracles/eth.toml"]
Sepolia and polygon failing because of this

2024-03-15 12:06 UTC, noisekit requested changes
Cannon change global weth config

2024-03-16 01:48 UTC, dbeal-eth commented
I made the change to the global config because we probably should be migrating all the feeds over to pyth anyway

2024-03-16 01:49 UTC, noisekit commented
> I made the change to the global config because we probably should be migrating all the feeds over to pyth anyway

Then we need to deprecate and delete old configs for sepolia and polygon or provide a way to migrate. As part of this pr.

2024-03-18 00:39 UTC, noisekit commented on tomls/collaterals/weth.toml
> -include = ["../oracles/eth.toml"]
fixed by removing nested includes

2024-03-18 00:41 UTC, noisekit commented on tomls/omnibus-arbitrum-mainnet-arbthetix/perps/feeCollector.toml
> +options.snx_token = "<%= imports.snx_mock_collateral.contracts.MintableToken.address %>"
we have plenty of references to `mock` in these configs.

2024-03-18 00:53 UTC, noisekit approved these changes
Fixed outstanding issues and make this PR non-breaking. Plus fixed few more copy-paste issues.

As it is deployed now and there is no cannon diff anymore - we can merge and all other changes will need new PRs.

2024-03-18 00:53 UTC, merged